# This file is used for the jupyterlite-sphinx extension
# See https://pipefunc.readthedocs.io/en/latest/lite/
name: pipefunc

channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - python
  # from pyproject.toml
  - networkx
  - psutil
  - versioningit
  - typing_extensions
  - cloudpickle
  # optional-dependencies: plotting
  - matplotlib
  - pip:
    - jupyterlite-xeus-python
